-- Active: 1673442535968@@127.0.0.1@3306@aplus_empresas

DROP TABLE IF EXISTS HHRRColaborador;

CREATE TABLE
    HHRRColaborador(
        Id int AUTO_INCREMENT primary key,
        Ci TEXT NULL,
        Nombre1 TEXT NULL,
        Nombre2 TEXT NULL,
        Nombre3 TEXT NULL,
        ApellidoPaterno TEXT NULL,
        ApellidoMaterno TEXT NULL,
        ApellidoCasado TEXT NULL,
        FechaNacimiento DATETIME NULL,
        VencimientoDocumento DATETIME NULL,
        VencimientoLicConducir DATETIME NULL,
        LugarNacimiento TEXT NULL,
        LicenciaConducir TEXT NULL,
        TelefonoFijo TEXT NULL,
        Celular TEXT NULL,
        TelefonoFijoTrabajo TEXT NULL,
        ContactoEmegencia TEXT NULL,
        TelefonoEmergencia TEXT NULL,
        ViviendaPropia TEXT NULL,
        VehiculoPropio TEXT NULL,
        TipoSangre TEXT NULL,
        FactorSangre TEXT NULL,
        Dirrecion TEXT NULL,
        Email TEXT NULL,
        TipoDocumento TEXT NULL,
        Nacionalidad TEXT NULL,
        Departamento TEXT NULL,
        EstadoCivil TEXT NULL,
        ConyugeNombreCompleto TEXT NULL,
        ConyugeLugarNacimiento TEXT NULL,
        ConyugeFechaNacimiento TEXT NULL,
        CodigoColaborador TEXT NULL,
        FechaIngreso DATETIME NULL,
        FechaIngresoVacaciones DATETIME NULL,
        FechaIngresoVacacionesAnt DATETIME NULL,
        FechaIngresoBonoAntiguedad DATETIME NULL,
        Oficina INT NULL,
        ModohaberBasico INT NULL,
        HaberBasico INT NULL,
        ModoQuincena INT NULL,
        HaberQuincena INT NULL,
        TelefonoLaboral INT NULL,
        CelularLaboral TEXT NULL,
        DirrecionLaboral INT NULL,
        EmailLaboral TEXT NULL,
        MotivoContrato TEXT NULL,
        FechaFinalizacion DATETIME NULL,
        FechaRatificacion DATETIME NULL,
        ExcliblePlanilla INT NULL,
        AguinaldoMes1 INT NULL,
        Aplica2aguinaldo INT NULL,
        AplicaRetroactivos INT NULL,
        AplicaPrima INT NULL,
        EnviarBoletaPago INT NULL,
        Indemnizacion INT NULL,
        PorcentajeCentroCosto INT NULL,
        CuentaBancaria INT NULL,
        AplicaAFP INT NULL,
        NroAFP INT NULL,
        Jubilado INT NULL,
        AportaAFP INT NULL,
        AplicaCajaSalud INT NULL,
        NroAsegurado TEXT NULL,
        Discapacidad INT NULL,
        RequiereApruebeVacaciones INT NULL,
        ValorLunes decimal NULL,
        ValorMartes decimal NULL,
        ValorMiercoles decimal NULL,
        ValorJueves decimal NULL,
        ValorViernes decimal NULL,
        ValorSabado decimal NULL,
        ValorDomingo decimal NULL,
        CodigoAsistencia INT NULL,
        DiasporMes INT NULL,
        ControlarAsistencia INT NULL,
        BonoExtra INT NULL,
        BonoExtraNocturna INT NULL,
        HorasParaHorasExtras INT NULL,
        HorasPorDia INT NULL,
        DescuentoPorFalta INT NULL,
        DescuentoPorAtraso INT NULL,
        Dominicales INT NULL,
        TrabajaDomingo INT NULL,
        HorasPlanillas INT NULL,
        Unidad INT NULL,
        Sucursal INT NULL,
        Cargo INT NULL,
        Clasificacionlaboral INT NULL,
        TipoContrato INT NULL,
        InformacionContable INT NULL,
        CentroCosto INT NULL,
        FormaPago INT NULL,
        TipoCuenta INT NULL,
        Banco INT NULL,
        AdministracionPensiones INT NULL,
        CajaSalud INT NULL,
        FormacionPrincial INT NULL,
        Sexo INT NULL
    );

INSERT INTO
    `hhrrcolaborador`(
        `Ci`,
        `Nombre1`,
        `Nombre2`,
        `Nombre3`,
        `ApellidoPaterno`,
        `ApellidoMaterno`,
        `ApellidoCasado`,
        `FechaNacimiento`,
        `VencimientoDocumento`,
        `VencimientoLicConducir`,
        `LugarNacimiento`,
        `LicenciaConducir`,
        `TelefonoFijo`,
        `Celular`,
        `TelefonoFijoTrabajo`,
        `ContactoEmegencia`,
        `TelefonoEmergencia`,
        `ViviendaPropia`,
        `VehiculoPropio`,
        `TipoSangre`,
        `FactorSangre`,
        `Dirrecion`,
        `Email`,
        `TipoDocumento`,
        `Nacionalidad`,
        `Departamento`,
        `EstadoCivil`,
        `ConyugeNombreCompleto`,
        `ConyugeLugarNacimiento`,
        `ConyugeFechaNacimiento`,
        `CodigoColaborador`,
        `FechaIngreso`,
        `FechaIngresoVacaciones`,
        `FechaIngresoVacacionesAnt`,
        `FechaIngresoBonoAntiguedad`,
        `Oficina`,
        `ModohaberBasico`,
        `HaberBasico`,
        `ModoQuincena`,
        `HaberQuincena`,
        `TelefonoLaboral`,
        `CelularLaboral`,
        `DirrecionLaboral`,
        `EmailLaboral`,
        `MotivoContrato`,
        `FechaFinalizacion`,
        `FechaRatificacion`,
        `ExcliblePlanilla`,
        `AguinaldoMes1`,
        `Aplica2aguinaldo`,
        `AplicaRetroactivos`,
        `AplicaPrima`,
        `EnviarBoletaPago`,
        `Indemnizacion`,
        `PorcentajeCentroCosto`,
        `CuentaBancaria`,
        `AplicaAFP`,
        `NroAFP`,
        `Jubilado`,
        `AportaAFP`,
        `AplicaCajaSalud`,
        `NroAsegurado`,
        `Discapacidad`,
        `RequiereApruebeVacaciones`,
        `ValorLunes`,
        `ValorMartes`,
        `ValorMiercoles`,
        `ValorJueves`,
        `ValorViernes`,
        `ValorSabado`,
        `ValorDomingo`,
        `CodigoAsistencia`,
        `DiasporMes`,
        `ControlarAsistencia`,
        `BonoExtra`,
        `BonoExtraNocturna`,
        `HorasParaHorasExtras`,
        `HorasPorDia`,
        `DescuentoPorFalta`,
        `DescuentoPorAtraso`,
        `Dominicales`,
        `TrabajaDomingo`,
        `HorasPlanillas`,
        `Unidad`,
        `Sucursal`,
        `Cargo`,
        `Clasificacionlaboral`,
        `TipoContrato`,
        `InformacionContable`,
        `CentroCosto`,
        `FormaPago`,
        `TipoCuenta`,
        `Banco`,
        `AdministracionPensiones`,
        `CajaSalud`,
        `FormacionPrincial`,
        `Sexo`
    )
VALUES (
        '[value-2]',
        '[value-3]',
        '[value-4]',
        '[value-5]',
        '[value-6]',
        '[value-7]',
        '[value-8]',
        '[value-9]',
        '[value-10]',
        '[value-11]',
        '[value-12]',
        '[value-13]',
        '[value-14]',
        '[value-15]',
        '[value-16]',
        '[value-17]',
        '[value-18]',
        '[value-19]',
        '[value-20]',
        '[value-21]',
        '[value-22]',
        '[value-23]',
        '[value-24]',
        '[value-25]',
        '[value-26]',
        '[value-27]',
        '[value-28]',
        '[value-29]',
        '[value-30]',
        '[value-31]',
        '[value-32]',
        '[value-33]',
        '[value-34]',
        '[value-35]',
        '[value-36]',
        '[value-37]',
        '[value-38]',
        '[value-39]',
        '[value-40]',
        '[value-41]',
        '[value-42]',
        '[value-43]',
        '[value-44]',
        '[value-45]',
        '[value-46]',
        '[value-47]',
        '[value-48]',
        '[value-49]',
        '[value-50]',
        '[value-51]',
        '[value-52]',
        '[value-53]',
        '[value-54]',
        '[value-55]',
        '[value-56]',
        '[value-57]',
        '[value-58]',
        '[value-59]',
        '[value-60]',
        '[value-61]',
        '[value-62]',
        '[value-63]',
        '[value-64]',
        '[value-65]',
        '[value-66]',
        '[value-67]',
        '[value-68]',
        '[value-69]',
        '[value-70]',
        '[value-71]',
        '[value-72]',
        '[value-73]',
        '[value-74]',
        '[value-75]',
        '[value-76]',
        '[value-77]',
        '[value-78]',
        '[value-79]',
        '[value-80]',
        '[value-81]',
        '[value-82]',
        '[value-83]',
        '[value-84]',
        '[value-85]',
        '[value-86]',
        '[value-87]',
        '[value-88]',
        '[value-89]',
        '[value-90]',
        '[value-91]',
        '[value-92]',
        '[value-93]',
        '[value-94]',
        '[value-95]',
        '[value-96]',
        '[value-97]',
        '[value-98]'
    )
SELECT *
from hhrrcolaborador;

SELECT
    c.id,
    c.Nombre1,
    c.Nombre2,
    c.Nombre3,
    c.ApellidoPaterno,
    c.ApellidoMaterno,
    c.ApellidoCasado,
    cargo.NombreCargo,
    unidad.NombreUnidad,
    sucursal.NombreSucursal,
    oficina.NombreOficina
FROM hhrrcolaborador as c
    inner JOIN hhrrcargo as cargo on cargo.id = c.Cargo
    INNER JOIN hhrrunidad as unidad on unidad.id = c.Unidad
    INNER JOIN hhrrsucursal as sucursal on sucursal.id = c.Sucursal
    INNER JOIN hhrroficina as oficina on c.Oficina = oficina.id