-- Active: 1673442535968@@127.0.0.1@3306@aplus_empresas

DROP TABLE IF EXISTS HHRRColaborador;

CREATE TABLE
    HHRRColaborador(
        Id int AUTO_INCREMENT primary key,
        Ci TEXT NULL,
        Nombre1 TEXT NULL,
        Nombre2 TEXT NULL,
        Nombre3 TEXT NULL,
        ApellidoPaterno TEXT NULL,
        ApellidoMaterno TEXT NULL,
        ApellidoCasado TEXT NULL,
        FechaNacimiento DATETIME NULL,
        VencimientoDocumento DATETIME NULL,
        VencimientoLicConducir DATETIME NULL,
        LugarNacimiento TEXT NULL,
        LicenciaConducir TEXT NULL,
        TelefonoFijo TEXT NULL,
        Celular TEXT NULL,
        TelefonoFijoTrabajo TEXT NULL,
        ContactoEmegencia TEXT NULL,
        TelefonoEmergencia TEXT NULL,
        ViviendaPropia INT NULL,
        VehiculoPropio INT NULL,
        TipoSangre TEXT NULL,
        FactorSangre TEXT NULL,
        Dirrecion TEXT NULL,
        Email TEXT NULL,
        HHRRTipoDocumentoId INT NULL,
        HHRRNacionalidadId INT NULL,
        HHRRDepartamentoId INT NULL,
        HHRREstadoCivilId INT NULL,
        ConyugeNombreCompleto TEXT NULL,
        ConyugeLugarNacimiento TEXT NULL,
        ConyugeFechaNacimiento TEXT NULL,
        CodigoColaborador TEXT NULL,
        FechaIngreso DATETIME NULL,
        FechaIngresoVacaciones DATETIME NULL,
        FechaIngresoVacacionesAnt DATETIME NULL,
        FechaIngresoBonoAntiguedad DATETIME NULL,
        HHRROficinaId INT NULL,
        ModohaberBasico INT NULL,
        HaberBasico DECIMAL(20,2) NULL,
        ModoQuincena INT NULL,
        HHRRModContratoId INT NULL,
        HaberQuincena DECIMAL(20,2) NULL,
        TelefonoLaboral TEXT NULL,
        CelularLaboral TEXT NULL,
        DirrecionLaboral TEXT NULL,
        EmailLaboral TEXT NULL,
        MotivoContrato TEXT NULL,
        FechaFinalizacion DATETIME NULL,
        FechaRatificacion DATETIME NULL,
        ExcliblePlanilla INT NULL,
        AguinaldoMes1 INT NULL,
        Aplica2aguinaldo INT NULL,
        AplicaRetroactivos INT NULL,
        AplicaPrima INT NULL,
        EnviarBoletaPago INT NULL,
        Indemnizacion INT NULL,
        PorcentajeCentroCosto DECIMAL(20,2) NULL,
        CuentaBancaria INT NULL,
        AplicaAFP INT NULL,
        NroAFP TEXT NULL,
        Jubilado INT NULL,
        AportaAFP INT NULL,
        AplicaCajaSalud INT NULL,
        NroAsegurado TEXT NULL,
        Discapacidad INT NULL,
        RequiereApruebeVacaciones INT NULL,
        ValorLunes DECIMAL(20,2) NULL,
        ValorMartes DECIMAL(20,2) NULL,
        ValorMiercoles DECIMAL(20,2) NULL,
        ValorJueves DECIMAL(20,2) NULL,
        ValorViernes DECIMAL(20,2) NULL,
        ValorSabado DECIMAL(20,2) NULL,
        ValorDomingo DECIMAL(20,2) NULL,
        CodigoAsistencia INT NULL,
        DiasporMes INT NULL,
        ControlarAsistencia INT NULL,
        BonoExtra INT NULL,
        BonoExtraNocturna INT NULL,
        HorasParaHorasExtras INT NULL,
        HorasPorDia INT NULL,
        DescuentoPorFalta INT NULL,
        DescuentoPorAtraso INT NULL,
        Dominicales INT NULL,
        TrabajaDomingo INT NULL,
        HorasPlanillas INT NULL,
        HHRRUnidadId INT NULL,
        HHRRSucursalId INT NULL,
        HHRRCargoId INT NULL,
        HHRRClasificacionLaboralId INT NULL,
        HHRRtipocontratoId INT NULL,
        HHRRInformacionContableId INT NULL,
        HHRRCentroCostoId INT NULL,
        HHRRFormaPagoId INT NULL,
        HHRRTipoCuentaId INT NULL,
        HHRRBancoId INT NULL,
        HHRRadministracionpesionId INT NULL,
        HHRRcajasaludId INT NULL,
        HHRRFormacionPrincipalId INT NULL,
        HHRRSexoId INT NULL
    );

INSERT INTO
    `hhrrcolaborador`(
        `Ci`,
        `Nombre1`,
        `Nombre2`,
        `Nombre3`,
        `ApellidoPaterno`,
        `ApellidoMaterno`,
        `ApellidoCasado`,
        `FechaNacimiento`,
        `VencimientoDocumento`,
        `VencimientoLicConducir`,
        `LugarNacimiento`,
        `LicenciaConducir`,
        `TelefonoFijo`,
        `Celular`,
        `TelefonoFijoTrabajo`,
        `ContactoEmegencia`,
        `TelefonoEmergencia`,
        `ViviendaPropia`,
        `VehiculoPropio`,
        `TipoSangre`,
        `FactorSangre`,
        `Dirrecion`,
        `Email`,
        `TipoDocumentoId`,
        `NacionalidadId`,
        `DepartamentoId`,
        `EstadoCivilId`,
        `ConyugeNombreCompleto`,
        `ConyugeLugarNacimiento`,
        `ConyugeFechaNacimiento`,
        `CodigoColaborador`,
        `FechaIngreso`,
        `FechaIngresoVacaciones`,
        `FechaIngresoVacacionesAnt`,
        `FechaIngresoBonoAntiguedad`,
        `OficinaId`,
        `ModohaberBasico`,
        `HaberBasico`,
        `ModoQuincena`,
        `HaberQuincena`,
        `TelefonoLaboral`,
        `CelularLaboral`,
        `DirrecionLaboral`,
        `EmailLaboral`,
        `MotivoContrato`,
        `FechaFinalizacion`,
        `FechaRatificacion`,
        `ExcliblePlanilla`,
        `AguinaldoMes1`,
        `Aplica2aguinaldo`,
        `AplicaRetroactivos`,
        `AplicaPrima`,
        `EnviarBoletaPago`,
        `Indemnizacion`,
        `PorcentajeCentroCosto`,
        `CuentaBancaria`,
        `AplicaAFP`,
        `NroAFP`,
        `Jubilado`,
        `AportaAFP`,
        `AplicaCajaSalud`,
        `NroAsegurado`,
        `Discapacidad`,
        `RequiereApruebeVacaciones`,
        `ValorLunes`,
        `ValorMartes`,
        `ValorMiercoles`,
        `ValorJueves`,
        `ValorViernes`,
        `ValorSabado`,
        `ValorDomingo`,
        `CodigoAsistencia`,
        `DiasporMes`,
        `ControlarAsistencia`,
        `BonoExtra`,
        `BonoExtraNocturna`,
        `HorasParaHorasExtras`,
        `HorasPorDia`,
        `DescuentoPorFalta`,
        `DescuentoPorAtraso`,
        `Dominicales`,
        `TrabajaDomingo`,
        `HorasPlanillas`,
        `UnidadId`,
        `SucursalId`,
        `CargoId`,
        `ClasificacionlaboralId`,
        `TipoContratoId`,
        `InformacionContableId`,
        `CentroCostoId`,
        `FormaPagoId`,
        `TipoCuentaId`,
        `BancoId`,
        `AdministracionPensionesId`,
        `CajaSaludId`,
        `FormacionPrincialId`,
        `SexoId`
    )
VALUES (
        '[value-2]',
        '[value-3]',
        '[value-4]',
        '[value-5]',
        '[value-6]',
        '[value-7]',
        '[value-8]',
        '[value-9]',
        '[value-10]',
        '[value-11]',
        '[value-12]',
        '[value-13]',
        '[value-14]',
        '[value-15]',
        '[value-16]',
        '[value-17]',
        '[value-18]',
        '[value-19]',
        '[value-20]',
        '[value-21]',
        '[value-22]',
        '[value-23]',
        '[value-24]',
        '[value-25]',
        '[value-26]',
        '[value-27]',
        '[value-28]',
        '[value-29]',
        '[value-30]',
        '[value-31]',
        '[value-32]',
        '[value-33]',
        '[value-34]',
        '[value-35]',
        '[value-36]',
        '[value-37]',
        '[value-38]',
        '[value-39]',
        '[value-40]',
        '[value-41]',
        '[value-42]',
        '[value-43]',
        '[value-44]',
        '[value-45]',
        '[value-46]',
        '[value-47]',
        '[value-48]',
        '[value-49]',
        '[value-50]',
        '[value-51]',
        '[value-52]',
        '[value-53]',
        '[value-54]',
        '[value-55]',
        '[value-56]',
        '[value-57]',
        '[value-58]',
        '[value-59]',
        '[value-60]',
        '[value-61]',
        '[value-62]',
        '[value-63]',
        '[value-64]',
        '[value-65]',
        '[value-66]',
        '[value-67]',
        '[value-68]',
        '[value-69]',
        '[value-70]',
        '[value-71]',
        '[value-72]',
        '[value-73]',
        '[value-74]',
        '[value-75]',
        '[value-76]',
        '[value-77]',
        '[value-78]',
        '[value-79]',
        '[value-80]',
        '[value-81]',
        '[value-82]',
        '[value-83]',
        '[value-84]',
        '[value-85]',
        '[value-86]',
        '[value-87]',
        '[value-88]',
        '[value-89]',
        '[value-90]',
        '[value-91]',
        '[value-92]',
        '[value-93]',
        '[value-94]',
        '[value-95]',
        '[value-96]',
        '[value-97]',
        '[value-98]'
    )
SELECT *
from hhrrcolaborador;

SELECT
    c.id,
    c.Nombre1,
    c.Nombre2,
    c.Nombre3,
    c.ApellidoPaterno,
    c.ApellidoMaterno,
    c.ApellidoCasado,
    cargo.NombreCargo,
    unidad.NombreUnidad,
    c.HaberBasico,
    c.HaberQuincena,
    c.ModohaberBasico,
    c.ModoQuincena,
    c.Clasificacionlaboral,
    c.MotivoContrato,
    c.FechaIngreso,
    c.FechaRatificacion,
    c.FechaFinalizacion,
    c.Aplica2aguinaldo,
    c.AguinaldoMes1,
    sucursal.NombreSucursal,
    c.ModoContrato,
    c.TipoContrato
FROM hhrrcolaborador as c
    inner JOIN hhrrcargo as cargo on cargo.id = c.Cargo
    INNER JOIN hhrrunidad as unidad on unidad.id = c.Unidad
    INNER JOIN hhrrsucursal as sucursal on sucursal.id = c.Sucursal